# Generated by Django 5.0.1 on 2024-03-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_web', '0006_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=400)),
                ('publish_date', models.DateField(null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default=598632, max_length=6),
        ),
    ]
