# Generated by Django 5.0.1 on 2024-03-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_web', '0007_property_details_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_details',
            name='image',
            field=models.ImageField(upload_to='uploaded_image'),
        ),
    ]
