# Generated by Django 5.0.1 on 2024-03-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_web', '0012_alter_property_details_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='email_address',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='contact_us',
            name='interact_as',
            field=models.CharField(default='', max_length=10),
        ),
    ]
