# Generated by Django 5.0.1 on 2024-04-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_web', '0013_contact_us_email_address_contact_us_interact_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='94aacc', max_length=6),
        ),
    ]
