# Generated by Django 5.0.1 on 2024-04-18 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_web', '0014_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_details',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='18f480', max_length=6),
        ),
    ]
