# Generated by Django 5.0.1 on 2024-04-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_web', '0015_property_details_address_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='9cb522', max_length=6),
        ),
    ]
