# Generated by Django 5.0.1 on 2024-04-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_web', '0016_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_name', models.CharField(max_length=20)),
                ('inquiry_email_address', models.CharField(max_length=50)),
                ('inquiry_phone_number', models.CharField(max_length=15)),
                ('inquiry_property_name', models.CharField(max_length=30)),
                ('property_id', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='cee5b2', max_length=6),
        ),
    ]
